import * as moment from 'moment';

export const constant = {
	nationality: [
		'Afghan',
		'Albanian',
		'Algerian',
		'American',
		'Andorran',
		'Angolan',
		'Antiguans',
		'Argentinean',
		'Armenian',
		'Australian',
		'Austrian',
		'Azerbaijani',
		'Bahamian',
		'Bahraini',
		'Bangladeshi',
		'Barbadian',
		'Barbudans',
		'Batswana',
		'Belarusian',
		'Belgian',
		'Belizean',
		'Beninese',
		'Bhutanese',
		'Bolivian',
		'Bosnian',
		'Brazilian',
		'British',
		'Bruneian',
		'Bulgarian',
		'Burkinabe',
		'Burmese',
		'Burundian',
		'Cambodian',
		'Cameroonian',
		'Canadian',
		'Cape Verdean',
		'Central African',
		'Chadian',
		'Chilean',
		'Chinese',
		'Colombian',
		'Comoran',
		'Congolese',
		'Costa Rican',
		'Croatian',
		'Cuban',
		'Cypriot',
		'Czech',
		'Danish',
		'Djibouti',
		'Dominican',
		'Dutch',
		'East Timorese',
		'Ecuadorean',
		'Egyptian',
		'Emirian',
		'Equatorial Guinean',
		'Eritrean',
		'Estonian',
		'Ethiopian',
		'Fijian',
		'Filipino',
		'Finnish',
		'French',
		'Gabonese',
		'Gambian',
		'Georgian',
		'German',
		'Ghanaian',
		'Greek',
		'Grenadian',
		'Guatemalan',
		'Guinea-Bissauan',
		'Guinean',
		'Guyanese',
		'Haitian',
		'Herzegovinian',
		'Honduran',
		'Hungarian',
		'Icelander',
		'Indian',
		'Indonesian',
		'Iranian',
		'Iraqi',
		'Irish',
		'Israeli',
		'Italian',
		'Ivorian',
		'Jamaican',
		'Japanese',
		'Jordanian',
		'Kazakhstani',
		'Kenyan',
		'Kittian and Nevisian',
		'Kuwaiti',
		'Kyrgyz',
		'Laotian',
		'Latvian',
		'Lebanese',
		'Liberian',
		'Libyan',
		'Liechtensteiner',
		'Lithuanian',
		'Luxembourger',
		'Macedonian',
		'Malagasy',
		'Malawian',
		'Malaysian',
		'Maldivan',
		'Malian',
		'Maltese',
		'Marshallese',
		'Mauritanian',
		'Mauritian',
		'Mexican',
		'Micronesian',
		'Moldovan',
		'Monacan',
		'Mongolian',
		'Moroccan',
		'Mosotho',
		'Motswana',
		'Mozambican',
		'Namibian',
		'Nauruan',
		'Nepalese',
		'New Zealander',
		'Ni-Vanuatu',
		'Nicaraguan',
		'Nigerien',
		'North Korean',
		'Northern Irish',
		'Norwegian',
		'Omani',
		'Pakistani',
		'Palauan',
		'Panamanian',
		'Papua New Guinean',
		'Paraguayan',
		'Peruvian',
		'Polish',
		'Portuguese',
		'Qatari',
		'Romanian',
		'Russian',
		'Rwandan',
		'Saint Lucian',
		'Salvadoran',
		'Samoan',
		'San Marinese',
		'Sao Tomean',
		'Saudi',
		'Scottish',
		'Senegalese',
		'Serbian',
		'Seychellois',
		'Sierra Leonean',
		'Singaporean',
		'Slovakian',
		'Slovenian',
		'Solomon Islander',
		'Somali',
		'South African',
		'South Korean',
		'Spanish',
		'Sri Lankan',
		'Sudanese',
		'Surinamer',
		'Swazi',
		'Swedish',
		'Swiss',
		'Syrian',
		'Taiwanese',
		'Tajik',
		'Tanzanian',
		'Thai',
		'Togolese',
		'Tongan',
		'Trinidadian or Tobagonian',
		'Tunisian',
		'Turkish',
		'Tuvaluan',
		'Ugandan',
		'Ukrainian',
		'Uruguayan',
		'Uzbekistani',
		'Venezuelan',
		'Vietnamese',
		'Welsh',
		'Yemenite',
		'Zambian',
		'Zimbabwean',
	],
	REQUEST_TYPES_OPTIONS: [
		{
			label: 'heading.cashAdvanceStatus',
			value: 'cashAdvance',
		},
		{
			label: 'heading.travelRequest',
			value: 'travelRequest',
		},
		{
			label: 'heading.expenseReimburse',
			value: 'expenseReimburse',
		},
	],
	REPORTS_TYPES_OPTIONS: [
		{
			label: 'heading.cashAdvanceStatus',
			value: 'cashAdvance',
		},
		{
			label: 'heading.travelRequest',
			value: 'travelRequest',
		},
		{
			label: 'heading.expenseReimburse',
			value: 'expenseReimburse',
		},
	],
	FILTERS: {
		REPORTS: [
			{
				label: 'components.filters.reports.employees',
				name: 'empId',
				options: [{ id: -1, name: 'components.filters.reports.myReports' },{ id: 0, name: 'components.filters.reports.all' }],
				defaultValue: -1,
				type: 'select',
				onlyIf: '',
				role: 'canManage',
			},
			{
				label: 'components.filters.reports.from',
				name: 'recordDateFrom',
				defaultValue: Date.now(),
				type: 'dateRange',
				onlyIf: '',
				role: null,
			},
			{
				label: 'components.filters.reports.to',
				name: 'recordDateTo',
				defaultValue: Date.now(),
				type: 'dateRange',
				onlyIf: '',
				role: null,
			},
			{
				label: 'components.filters.reports.amount',
				name: 'amount',
				options: [{ id: 0, name: 'components.filters.reports.all' }],
				defaultValue: [10, 100000],
				type: 'range',
				splitField: ['amountFrom', 'amountTo'],
				onlyIf: '',
				role: null,
			},

			{
				label: 'components.filters.reports.status',
				name: 'approvalStatusId',
				options: [{ id: 0, name: 'components.filters.reports.all' }],
				defaultValue: 0,
				type: 'select',
				onlyIf: '',
				role: null,
			},

			{
				label: 'components.filters.reports.project',
				name: 'projectId',
				options: [{ id: 0, name: 'components.filters.reports.all'}],
				defaultValue: 0,
				type: 'select',
				onlyIf: '',
				role: 'canManage',
			},
			{
				label: 'components.filters.reports.subProject',
				name: 'subProjectId',
				options: [{ id: 0, name: 'components.filters.reports.all' }],
				defaultValue: 0,
				type: 'select',
				onlyIf: 'projectId',
				role: 'canManage',
			},
			{
				label: 'components.filters.reports.task',
				name: 'workTaskId',
				options: [{ id: 0, name: 'components.filters.reports.all' }],
				defaultValue: 0,
				type: 'select',
				onlyIf: 'subProjectId',
				role: 'canManage',
			},
			{
				label: 'components.filters.reports.costCenter',
				name: 'costCenterId',
				options: [{ id: 0, name: 'components.filters.reports.all' }],
				defaultValue: 0,
				type: 'select',
				onlyIf: '',
				role: 'canOrganize',
			},
			{
				label: 'components.filters.reports.department',
				name: 'departmentId',
				options: [{ id: 0, name: 'components.filters.reports.all'}],
				defaultValue: 0,
				type: 'select',
				onlyIf: 'costCenterId',
				role: 'canOrganize',
			},
		],
		SUB_CLAIMS: [
			{
				label: 'components.filters.reports.employees',
				name: 'empId',
				options: [{ id: -1, name: 'components.filters.reports.myReports' },{ id: 0, name: 'components.filters.reports.all' }],
				defaultValue: -1,
				type: 'select',
				onlyIf: '',
				role: null,
			},
			{
				label: 'components.filters.reports.expenseType',
				name: 'expenseTypeId',
				options: [{ id: 0, name: 'components.filters.reports.all' }],
				defaultValue: 0,
				type: 'select',
				onlyIf: '',
				role: null,
			},
			{
				label: 'components.filters.reports.from',
				name: 'recordDateFrom',
				defaultValue: Date.now(),
				type: 'dateRange',
				onlyIf: '',
				role: null,
			},
			{
				label: 'components.filters.reports.to',
				name: 'recordDateTo',
				defaultValue: Date.now(),
				type: 'dateRange',
				onlyIf: '',
				role: null,
			},
			{
				label: 'components.filters.reports.amount',
				name: 'amount',
				defaultValue: [10, 100000],
				type: 'range',
				splitField: ['expenseReimbClaimAmountFrom', 'expenseReimbClaimAmountTo'],
				onlyIf: '',
				role: null,
			},

			{
				label: 'components.filters.reports.status',
				name: 'approvalStatusId',
				options: [{ id: 0, name: 'components.filters.reports.all' }],
				defaultValue: 0,
				type: 'select',
				onlyIf: '',
				role: null,
			},

		],
		TRAVEL_FILTER: [
			{
				label: 'components.filters.reports.employees',
				name: 'empId',
				options: [{ id: -1, name: 'components.filters.reports.myReports' },{ id: 0, name: 'components.filters.reports.all' }],
				defaultValue: -1,
				type: 'select',
				onlyIf: '',
				role: 'canManage',
			},
			{
				label: 'components.filters.reports.from',
				name: 'recordDateFrom',
				defaultValue: Date.now(),
				type: 'dateRange',
				onlyIf: '',
				role: null,
			},
			{
				label: 'components.filters.reports.to',
				name: 'recordDateTo',
				defaultValue: Date.now(),
				type: 'dateRange',
				onlyIf: '',
				role: null,
			},
			{
				label: 'components.filters.reports.travelFrom',
				name: 'travelStartDate',
				defaultValue: Date.now(),
				type: 'dateRange',
				onlyIf: '',
				role: null,
			},
			{
				label: 'components.filters.reports.travelTo',
				name: 'travelEndDate',
				defaultValue: Date.now(),
				type: 'dateRange',
				onlyIf: '',
				role: null,
			},
			{
				label: 'components.filters.reports.status',
				name: 'currentStatus',
				options: [{ id: 0, name: 'components.filters.reports.all' }],
				defaultValue: 0,
				type: 'select',
				onlyIf: '',
				role: null,
			},
			{
				label: 'components.filters.reports.travelPurpose',
				name: 'travelPurpose',
				defaultValue: '',
				type: 'text',
				onlyIf: '',
				role: null,
			},
			{
				label: 'components.filters.reports.project',
				name: 'projectId',
				options: [{ id: 0, name: 'components.filters.reports.all' }],
				defaultValue: 0,
				type: 'select',
				onlyIf: '',
				role: 'canManage',
			},
			{
				label: 'components.filters.reports.subProject',
				name: 'subProjectId',
				options: [{ id: 0, name: 'components.filters.reports.all' }],
				defaultValue: 0,
				type: 'select',
				onlyIf: 'projectId',
				role: 'canManage',
			},
			{
				label: 'components.filters.reports.task',
				name: 'workTaskId',
				options: [{ id: 0, name: 'components.filters.reports.all' }],
								defaultValue: 0,
				type: 'select',
				onlyIf: 'subProjectId',
				role: 'canManage',
			},
			{
				label: 'components.filters.reports.costCenter',
				name: 'costCenterId',
				options: [{ id: 0, name: 'components.filters.reports.all' }],
				defaultValue: 0,
				type: 'select',
				onlyIf: '',
				role: 'canOrganize',
			},
			{
				label: 'components.filters.reports.department',
				name: 'departmentId',
				options: [{ id: 0, name: 'components.filters.reports.all' }],
				defaultValue: 0,
				type: 'select',
				onlyIf: 'costCenterId',
				role: 'canOrganize',
			},
		],
		EMPLOYEES: [
			{
				label: 'components.filters.reports.employeeName',
				name: 'employeeName',
				defaultValue: '',
				type: 'text',
				onlyIf: '',
				role: null,
			},
			{
				label: 'components.filters.reports.employeeCode',
				name: 'empCode',
				defaultValue: '',
				type: 'text',
				onlyIf: '',
				role: null,
			},
			{
				label: 'components.filters.reports.bankAccount',
				name: 'bankAccount',
				defaultValue: '',
				type: 'text',
				onlyIf: '',
				role: null,
			},

			{
				label: 'components.filters.reports.nationalId',
				name: 'nationalID',
				defaultValue: '',
				type: 'text',
				onlyIf: '',
				role: null,
			},

			{
				label: 'components.filters.reports.passportNo',
				name: 'passportNo',
				defaultValue: '',
				type: 'text',
				onlyIf: '',
				role: null,
			},

			{
				label: 'components.filters.reports.taxNo',
				name: 'taxNumber',
				defaultValue: '',
				type: 'text',
				onlyIf: '',
				role: null,
			},

			{
				label: 'components.filters.reports.nationality',
				name: 'nationality',
				options: [{ id: 0, name: 'components.filters.reports.all' }],
				defaultValue: 0,
				type: 'select',
				onlyIf: '',
				role: null,
			},
			{
				label: 'components.filters.reports.gender',
				name: 'gender',
				options: [
					{ id: 0, name: 'components.filters.reports.all' },
					{ id: 'male', name: 'components.filters.reports.male' },
					{ id: 'female', name: 'components.filters.reports.female' },
					{ id: 'unknown', name: 'components.filters.reports.others' },
				],
				defaultValue: 0,
				type: 'select',
				onlyIf: '',
				role: null,
			},
			{
				label: 'components.filters.reports.email',
				name: 'email',
				defaultValue: '',
				type: 'text',
				onlyIf: '',
				role: null,
			},
			{
				label: 'components.filters.reports.mobileNo',
				name: 'mobileNumber',
				defaultValue: '',
				type: 'text',
				onlyIf: '',
				role: null,
			},
			{
				label: 'components.filters.reports.employmentType',
				name: 'employmentTypeId',
				options: [{ id: 0, name: 'components.filters.reports.all' }],
				defaultValue: 0,
				type: 'select',
				onlyIf: '',
				role: null,
			},
			{
				label: 'components.filters.reports.jobRole',
				name: 'jobRoleId',
				options: [{ id: 0, name: 'All' }],
				defaultValue: 0,
				type: 'select',
				onlyIf: '',
				role: null,
			},
			{
				label: 'components.filters.reports.approvalGroup',
				name: 'approvalGroupId',
				options: [{ id: 0, name: 'components.filters.reports.all' }],
				defaultValue: 0,
				type: 'select',
				onlyIf: '',
				role: null,
			},
			{
				label: 'components.filters.reports.department',
				name: 'departmentId',
				options: [{ id: 0, name: 'components.filters.reports.all' }],
				defaultValue: 0,
				type: 'select',
				onlyIf: '',
				role: null,
			},
			{
				label: 'components.filters.reports.status',
				name: 'statusTypeId',
				options: [{ id: 0, name: 'components.filters.reports.all' }],
				defaultValue: 0,
				type: 'select',
				onlyIf: '',
				role: null,
			},
		],
		USERS: [
			{
				label: 'components.filters.reports.roleId',
				name: 'roleId',
				options: [{ id: 0, name: 'components.filters.reports.all' }],
				defaultValue: "",
				type: 'select',
				onlyIf: '',
				role: null,
			},
		],
	},

	DISBURSE: {
		FILTER:[
			{
				label: 'components.filters.reports.all',
				value: 'all',
			},
			{
				label: 'components.filters.reports.settled',
				value: true,
			},
			{
				label: 'components.filters.reports.notSettled',
				value: false,
			},
		],
		FORM:[
			{
				label: 'form.disburse.comment',
				name: 'settlementComment',
				defaultValue: '',
				type: 'text',
				onlyIf: '',
				role: null,
				required:true
			},
			{
				label: 'form.disburse.additionalData',
				name: 'additionalData',
				defaultValue: '',
				type: 'text',
				onlyIf: '',
				role: null,
				required:true
			},
		]
	}
};
